export const veiculosP = [
  {
    Meio_de_transporte: 'Carro',
    Combustível_Tipo: 'Diesel',
    Combustível: '0',
    Potência_do_motor: '1.0 à 1.5',
    Modelo: '0',
    Quilometragem: 0,
    co2: 0,
    id: 0,
  },
  {
    Meio_de_transporte: 'Carro',
    Combustível_Tipo: 'Diesel',
    Combustível: '0',
    Potência_do_motor: '1.6 à 2.0',
    Modelo: '0',
    Quilometragem: 0,
    co2: 0,
    id: 1,
  },
  {
    Meio_de_transporte: 'Carro',
    Combustível_Tipo: 'Diesel',
    Combustível: '0',
    Potência_do_motor: 'Maior que 2.0',
    Modelo: '0',
    Quilometragem: 0,
    co2: 224,
    id: 2,
  },
  {
    Meio_de_transporte: 'Carro',
    Combustível_Tipo: 'Etanol',
    Combustível: '0',
    Potência_do_motor: '1.0 à 1.5',
    Modelo: '0',
    Quilometragem: 0,
    co2: 1.4,
    id: 3,
  },
  {
    Meio_de_transporte: 'Carro',
    Combustível_Tipo: 'Etanol',
    Combustível: '0',
    Potência_do_motor: '1.6 à 2.0',
    Modelo: '0',
    Quilometragem: 0,
    co2: 1.9,
    id: 4,
  },
  {
    Meio_de_transporte: 'Carro',
    Combustível_Tipo: 'Etanol',
    Combustível: '0',
    Potência_do_motor: 'Maior que 2.0',
    Modelo: '0',
    Quilometragem: 0,
    co2: 2.9,
    id: 5,
  },
  {
    Meio_de_transporte: 'Carro',
    Combustível_Tipo: 'Gasolina',
    Combustível: '0',
    Potência_do_motor: '1.0 à 1.5',
    Modelo: '0',
    Quilometragem: 0,
    co2: 128,
    id: 6,
  },
  {
    Meio_de_transporte: 'Carro',
    Combustível_Tipo: 'Gasolina',
    Combustível: '0',
    Potência_do_motor: '1.6 à 2.0',
    Modelo: '0',
    Quilometragem: 0,
    co2: 169,
    id: 7,
  },
  {
    Meio_de_transporte: 'Carro',
    Combustível_Tipo: 'Gasolina',
    Combustível: '0',
    Potência_do_motor: 'Maior que 2.0',
    Modelo: '0',
    Quilometragem: 0,
    co2: 247,
    id: 8,
  },
  {
    Meio_de_transporte: 'Carro',
    Combustível_Tipo: 'GNV',
    Combustível: '0',
    Potência_do_motor: '1.0 à 1.5',
    Modelo: '0',
    Quilometragem: 0,
    co2: 137,
    id: 9,
  },
  {
    Meio_de_transporte: 'Carro',
    Combustível_Tipo: 'GNV',
    Combustível: '0',
    Potência_do_motor: '1.6 à 2.0',
    Modelo: '0',
    Quilometragem: 0,
    co2: 163,
    id: 10,
  },
  {
    Meio_de_transporte: 'Carro',
    Combustível_Tipo: 'GNV',
    Combustível: '0',
    Potência_do_motor: 'Maior que 2.0',
    Modelo: '0',
    Quilometragem: 0,
    co2: 235,
    id: 11,
  },
  {
    Meio_de_transporte: 'Carro',
    Combustível_Tipo: 'Elétrico',
    Combustível: '0',
    Potência_do_motor: '0',
    Modelo: 'Renault Zoe',
    Quilometragem: 0,
    co2: 10.3,
    id: 12,
  },
  {
    Meio_de_transporte: 'Carro',
    Combustível_Tipo: 'Elétrico',
    Combustível: '0',
    Potência_do_motor: '0',
    Modelo: 'Cerry Arrizo 5e',
    Quilometragem: 0,
    co2: 12.3,
    id: 13,
  },
  {
    Meio_de_transporte: 'Carro',
    Combustível_Tipo: 'Elétrico',
    Combustível: '0',
    Potência_do_motor: '0',
    Modelo: 'JAC iEV40',
    Quilometragem: 0,
    co2: 10,
    id: 14,
  },
  {
    Meio_de_transporte: 'Carro',
    Combustível_Tipo: 'Elétrico',
    Combustível: '0',
    Potência_do_motor: '0',
    Modelo: 'Nissan Leaf',
    Quilometragem: 0,
    co2: 7.7,
    id: 15,
  },
  {
    Meio_de_transporte: 'Carro',
    Combustível_Tipo: 'Elétrico',
    Combustível: '0',
    Potência_do_motor: '0',
    Modelo: 'BMW i3',
    Quilometragem: 0,
    co2: 9.4,
    id: 16,
  },
  {
    Meio_de_transporte: 'Carro',
    Combustível_Tipo: 'Elétrico',
    Combustível: '0',
    Potência_do_motor: '0',
    Modelo: 'Chevrolet Bolt',
    Quilometragem: 0,
    co2: 11.9,
    id: 17,
  },
  {
    Meio_de_transporte: 'Carro',
    Combustível_Tipo: 'Elétrico',
    Combustível: '0',
    Potência_do_motor: '0',
    Modelo: 'Jaguar I-Pace',
    Quilometragem: 0,
    co2: 14.4,
    id: 18,
  },
  {
    Meio_de_transporte: 'Carro',
    Combustível_Tipo: 'Elétrico',
    Combustível: '0',
    Potência_do_motor: '0',
    Modelo: 'Outro',
    Quilometragem: 0,
    co2: 10.6,
    id: 19,
  },
  {
    Meio_de_transporte: 'Carro',
    Combustível_Tipo: 'Híbrido',
    Combustível: 'Gasolina',
    Potência_do_motor: '0',
    Modelo: '0',
    Quilometragem: 0,
    co2: 84.5,
    id: 20,
  },
  {
    Meio_de_transporte: 'Carro',
    Combustível_Tipo: 'Híbrido',
    Combustível: 'Diesel',
    Potência_do_motor: '0',
    Modelo: '0',
    Quilometragem: 0,
    co2: 118.5,
    id: 21,
  },
  {
    Meio_de_transporte: 'Carro',
    Combustível_Tipo: 'Híbrido',
    Combustível: 'Etanol',
    Potência_do_motor: '0',
    Modelo: '0',
    Quilometragem: 0,
    co2: 0.65,
    id: 22,
  },
  {
    Meio_de_transporte: 'Moto',
    Combustível_Tipo: 'Gasolina',
    Combustível: '0',
    Potência_do_motor: 'Até 125cc',
    Modelo: '0',
    Quilometragem: 0,
    co2: 60,
    id: 23,
  },
  {
    Meio_de_transporte: 'Moto',
    Combustível_Tipo: 'Gasolina',
    Combustível: '0',
    Potência_do_motor: '126cc à 250cc',
    Modelo: '0',
    Quilometragem: 0,
    co2: 68,
    id: 24,
  },
  {
    Meio_de_transporte: 'Moto',
    Combustível_Tipo: 'Gasolina',
    Combustível: '0',
    Potência_do_motor: 'Maior que 250cc',
    Modelo: '0',
    Quilometragem: 0,
    co2: 94,
    id: 25,
  },
  {
    Meio_de_transporte: 'Moto',
    Combustível_Tipo: 'Etanol',
    Combustível: '0',
    Potência_do_motor: 'Até 125cc',
    Modelo: '0',
    Quilometragem: 0,
    co2: 0.7,
    id: 26,
  },
  {
    Meio_de_transporte: 'Moto',
    Combustível_Tipo: 'Etanol',
    Combustível: '0',
    Potência_do_motor: '126cc à 250cc',
    Modelo: '0',
    Quilometragem: 0,
    co2: 0.8,
    id: 27,
  },
  {
    Meio_de_transporte: 'Moto',
    Combustível_Tipo: 'Etanol',
    Combustível: '0',
    Potência_do_motor: 'Maior que 250cc',
    Modelo: '0',
    Quilometragem: 0,
    co2: 1.1,
    id: 28,
  },
  {
    Meio_de_transporte: 'Bicicleta',
    Combustível_Tipo: '0',
    Combustível: '0',
    Potência_do_motor: '0',
    Modelo: '0',
    Quilometragem: 0,
    co2: 0,
    id: 29,
  },
  {
    Meio_de_transporte: 'Bicicleta elétrica',
    Combustível_Tipo: '0',
    Combustível: '0',
    Potência_do_motor: '0',
    Modelo: '0',
    Quilometragem: 0,
    co2: 0.47,
    id: 30,
  },
  {
    Meio_de_transporte: 'Patinete elétrico',
    Combustível_Tipo: '0',
    Combustível: '0',
    Potência_do_motor: '0',
    Modelo: '0',
    Quilometragem: 0,
    co2: 0.84,
    id: 31,
  },
]

export function vp() {}
